
name: Practica 4 - Integracion Continua

on:
  push:
    branches:
      - main

jobs:
  notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificacion
        run: |
          curl --fail-with-body --retry 3 \
            -H "Title: Practica 4 - ITLA" \
            -H "Tags: white_check_mark" \
            -d "Nueva actualizacion en GitHub - Oskarling Mendez" \
            https://ntfy.sh/devops-itla
